### ISSUE TITLE
New SO navigation: inbox and achievement boxes misaligned after AJAX load

### ISSUE THREAD

**Issue by mjpieters** [vyznev/soup#29]
When you opt-in to the new SO navigation (see https://meta.stackoverflow.com/questions/343103/help-test-the-new-top-nav-phase-3-testing-runs-this-week), the inbox and achievent boxes *jump* after ajax load completes:

![](https://i.stack.imgur.com/fdkPs.gif)

Just to be clear: the box should not load empty in one location, then jump to another.

This only happens when SOUP is enabled in tampermonkey. When I disable SOUP, the boxes stay put.

Tested on macOS Sierra 10.12.2, Chrome 55.0.2883.95

**Comment by vyznev** [comment]
Thanks for the report! It seems the [mse207526](http://meta.stackexchange.com/q/207526) fix isn't compatible with the new topbar. I've just committed a new SOUP version into the devel branch that disables that fix when using the new topbar. I'll consider backporting it into the stable branch as well, but honestly, what I really should do is just push the whole accumulated backlog of changes from the devel branch into stable and call it v1.46.

**Comment by vyznev** [comment]
With v1.46 released, this should now be fixed in the stable branch too.
