### ISSUE TITLE
Incompatible with Chatjax++

### ISSUE THREAD

**Issue by Sir-Cumference** [vyznev/soup#34]
Sadly, SOUP seems to prevent [Chatjax++](https://github.com/vyznev/chatjax) from loading. Could you fix this?

Thanks.

**Comment by vyznev** [comment]
Oops, that's embarrassing. I thought I'd removed the SOUP dependency from ChatJax++ a long time ago, but I forgot that I'd never merged those changes into the master branch. And SOUP v1.52 broke the interface which the older version of ChatJax++ was depending on.

Anyway, upgrading ChatJax++ to v0.3 (just officially released a few minutes ago) should fix the problem.

**Comment by Sir-Cumference** [comment]
@vyznev Works now, thanks! :)
