### ISSUE TITLE
Redundant link - "see all inbox items" - in Notification Inbox

### ISSUE THREAD

**Issue by GaurangTandon** [vyznev/soup#38]
`soup-mse223737-link` is redundant as SE already provides a `<a href="https://stackexchange.com/users/USER_ID?tab=inbox">all items</a>` to the right side of the Notification Inbox.

Screenshot:

![image](https://user-images.githubusercontent.com/6308683/41305794-a6a21bc0-6e91-11e8-95ba-2f8a610e48ab.png)

**Comment by vyznev** [comment]
Thanks for pointing this out! The redundant fix will be gone in SOUP v1.54.
