### ISSUE TITLE
Don't make links to http://elections.stackoverflow.com protocol relative

### ISSUE THREAD

**Issue by mjpieters** [vyznev/soup#4]
The site doesn't serve over HTTPS, so the link from [election pages](https://stackoverflow.com/election/6) is broken when SOUP is active.

Can an exception be added for this or is that counter-productive?

**Comment by vyznev** [comment]
Thanks for reporting this! It should be fixed in SOUP 1.28.2 / 1.29.16.

**Comment by mjpieters** [comment]
Thanks! Fix confirmed.

**Comment by wf34t35f** [comment]
FUCK OFF YOURSELF @mjpieters @thefourtheye @ztane @Ffisegydd @vaultah
