### ISSUE TITLE
Reduce the time to load spoiler text as it used to be originally 

### ISSUE THREAD

**Issue by GaurangTandon** [vyznev/soup#40]
I find the implementation of the placeholder text ("spoiler: hover/click to reveal") a bit unproductive. With SOUP enabled, I've to wait a bit _longer_ to view what's inside the spoiler. First the placeholder text ("spoiler: hover/click to reveal") fades out, and only _then_ the spoiler text fades in. 

I am pretty sure that the time taken for the spoiler text to load is longer than it used to be without SOUP enabled. Is there a way to reduce the time to load spoiler text as it used to be originally (without SOUP)?

**Comment by vyznev** [comment]
As of version 1.54, SOUP no longer includes any spoiler-related fixes, as the native SE spoiler implementation has been considerably improved and now incorporates most of the features of the SOUP version.

One minor feature that got lost in the process is the "spoiler: hover/click to reveal" hint text.  But at least not having the text also means that fading it out no longer delays the appearance of the spoiler content. :)
