### ISSUE TITLE
Remove mse322619 fix

### ISSUE THREAD

**Issue by gparyani** [vyznev/soup#45]
Per https://meta.stackexchange.com/a/332571/377214, mse322619 is now fixed in the SE engine. Please remove it from SOUP.

**Comment by vyznev** [comment]
Thanks for the heads-up. This looks non-urgent, as the redundant fix in SOUP doesn't seem to be causing any harm, but I'll make a note of this and remove it from the next stable release.

(Also, I'm not 100% sure the SE fix is working quite as intended; see my comment on Shog's answer.)

**Comment by gparyani** [comment]
This was added to the development branch in 11d1ade.
